### ISSUE TITLE
Diversified search engines

### ISSUE THREAD

**Issue by 1natsu172** [ErgoFriend/Quiqsearch#2]
The current implementation is for the Google engine only. It would be better to use the user's default search engine. `browser.search` API would be available.

- `search.query`
  - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search/query
- `search.search`
  - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search/search
  - More advanced, but now firefox only

Or, it could be designed so that the user sets the search query in config.

**Comment by ergofriend** [comment]
I didn't know search API. Looks useful.
